import '../style.css';
import reference from '../tests/python-reference.json';
import { Aircraft,DEFAULT_POLICY,SafetyPolicy,WorldState,conflictPairs,projected } from './core';
import { createAircraft,conflictWindows,parseWorldState } from './world-tools';
import { Advisory } from './planner';
import { towerPython } from './python';
import { AuditLog } from './audit';
import { Ack,Approval,GateRejected } from './gate';
import { AuditEvent } from './audit';
import { drawAirspace,viewRange } from './draw';
type Scenario={name:string;state:WorldState;now:number};
const fixture=(reference as unknown as {scenarios:Scenario[]}).scenarios[0]!;
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const copy=(s:WorldState):WorldState=>JSON.parse(JSON.stringify(s)) as WorldState;
let policy:SafetyPolicy={...DEFAULT_POLICY};
let state=copy(fixture.state),now=fixture.now,selected='TWR419',running=false,pending:Advisory|null=null,approval:Approval|null=null,audit=new AuditLog();
let rate=1,lastFrame=0,trafficSeq=0,busy=false,pythonAudit='[]';
type GateState='wait'|'done'|'fail'; let gateScreen:GateState='wait',gateApproval:GateState='wait',gateAck:GateState='wait';
function setText(id:string,value:string){$(id).textContent=value;}
function gate(id:string,status:'wait'|'done'|'fail',label:string){const node=$(id);node.className=`gate-step ${status}`;const i=node.querySelector('i');if(i)i.textContent=label;}
function drawLists(pairs:Array<[string,string]>){
 const flights=$('flight-list');flights.replaceChildren();
 for(const a of state.aircraft){const row=document.createElement('div');row.className=`flight-row ${selected===a.aircraft_id?'selected':''}`;const b=document.createElement('button');b.textContent=a.aircraft_id;b.onclick=()=>{selected=a.aircraft_id;render();};const meta=document.createElement('span');meta.className='flight-meta';meta.textContent=`${Math.round(a.altitude_ft/100)} FL / ${a.vx_nm_min.toFixed(1)}, ${a.vy_nm_min.toFixed(1)} NM/M`;row.append(b,meta);flights.append(row);}
 const watch=$('conflict-list');watch.replaceChildren();
 for(const [a,b] of pairs){const row=document.createElement('div');row.className='conflict-row';const label=document.createElement('span');label.textContent=`${a} / ${b}`;const meta=document.createElement('span');meta.className='conflict-meta';meta.textContent='HORIZONTAL + VERTICAL';row.append(label,meta);watch.append(row);}
 if(!pairs.length){const p=document.createElement('p');p.className='fine-print';p.textContent='No pair enters both unsafe intervals inside the policy horizon.';watch.append(p);}
 setText('flight-count',`${state.aircraft.length} FLIGHTS`);
}
let proposalMessage='No proposal yet. The planner only returns a setpoint if it clears the separation policy.';
async function render():Promise<void>{
 const pairs=conflictPairs(state,policy);drawAirspace($<HTMLCanvasElement>('airspace'),state,selected,policy);drawLists(pairs);
 const badge=$('world-badge');badge.className=`badge ${pairs.length?'alert':'safe'}`;badge.textContent=pairs.length?'ACTION':'CLEAR';
 setText('world-title',pairs.length?`${pairs.length} conflict pair${pairs.length===1?'':'s'} inside policy envelope`:'No projected conflict');
 setText('world-note',pairs.length?'Horizontal and vertical unsafe-time intervals overlap inside the active policy horizon.':'No simultaneous horizontal and vertical intrusion inside the active policy horizon.');
 setText('pair-count',String(pairs.length));setText('policy-window',`${policy.horizon_min.toFixed(1)} MIN`);setText('range-label',`RANGE +/- ${viewRange(state,policy)} NM`);setText('projection-label',`${policy.horizon_min.toFixed(1)} MIN PROJECTION`);const first=conflictWindows(state,policy)[0];setText('conflict-time',first?`T+${(first.start_min*60).toFixed(0)} SEC`:'CLEAR');setText('conflict-detail',first?`${first.aircraft_a} / ${first.aircraft_b} share ${first.start_min.toFixed(2)} to ${first.end_min.toFixed(2)} min. Midpoint: ${first.horizontal_nm.toFixed(2)} NM / ${first.vertical_ft.toFixed(0)} FT.`:'No simultaneous loss of separation. Add traffic or tighten the envelope.');setText('policy-stat-horizontal',policy.min_horizontal_nm.toFixed(1));setText('policy-stat-vertical',policy.min_vertical_ft.toLocaleString('en-US'));setText('policy-stat-horizon',policy.horizon_min.toFixed(1));const editor=$<HTMLTextAreaElement>('world-json');if(document.activeElement!==editor)editor.value=JSON.stringify(state,null,2);setText('sim-clock',`T+${Math.max(0,Math.floor(now-fixture.now))} SEC`);setText('speed-value',`${rate.toFixed(1)}x`);
 setText('proposal-state',pending?'PROPOSAL READY':pairs.length?'NEEDS REVIEW':'IDLE');
 if(pending)setText('proposal-output',`${pending.aircraft_id} -> vx ${pending.set_vx_nm_min.toFixed(1)} / vy ${pending.set_vy_nm_min.toFixed(1)} NM/M / climb ${pending.set_climb_ft_min} FT/M. Bound to ${pending.world_hash.slice(0,10)}.`);else setText('proposal-output',proposalMessage);
 gate('gate-screen',gateScreen,gateScreen==='done'?'PASS':gateScreen==='fail'?'FAIL':'WAIT');gate('gate-approval',gateApproval,gateApproval==='done'?'APPROVED':gateApproval==='fail'?'REJECTED':'WAIT');gate('gate-ack',gateAck,gateAck==='done'?'ACCEPTED':gateAck==='fail'?'REJECTED':'WAIT');
 $('run-planner').toggleAttribute('disabled',busy||!pairs.length||!!pending);$('approve').toggleAttribute('disabled',!pending||!!approval);$('readback').toggleAttribute('disabled',busy||!pending||!approval);$('toggle-run').toggleAttribute('disabled',busy||!!pending);
 for(const id of ['reset-world','add-traffic','add-custom-flight','remove-selected','perturb-track','load-world','policy-horizontal','policy-vertical','policy-horizon'])$(id).toggleAttribute('disabled',busy);
 const valid=await audit.verify();setText('audit-status',`${audit.events.length} EVENT${audit.events.length===1?'':'S'} / ${valid?'VALID':'BROKEN'}`);
 const list=$('audit-events');list.replaceChildren();for(const e of audit.events){const li=document.createElement('li');li.textContent=`${String(e.seq).padStart(2,'0')}  ${e.kind}  ${JSON.stringify(e.payload).slice(0,120)}  ${e.event_hash.slice(0,12)}`;list.append(li);}
}

function clearPending(message:string){pending=null;approval=null;proposalMessage=message;gateScreen='wait';gateApproval='wait';gateAck='wait';}
function addTraffic(){running=false;clearPending('Traffic added. The planner will evaluate the changed world, not an animation script.');let id:string;do{id=`TWR${820+trafficSeq}`;trafficSeq++;}while(state.aircraft.some(a=>a.aircraft_id===id));state={version:state.version+1,observed_at:now,aircraft:[...state.aircraft,{aircraft_id:id,x_nm:0,y_nm:-5,altitude_ft:10000,vx_nm_min:0,vy_nm_min:1,climb_ft_min:0}]};selected=id;void render();}
function addCustomFlight(){running=false;try{const num=(id:string)=>$<HTMLInputElement>(id).valueAsNumber;const flight=createAircraft({aircraft_id:$<HTMLInputElement>('flight-id').value,x_nm:num('flight-x'),y_nm:num('flight-y'),altitude_ft:num('flight-level')*100,heading_deg:num('flight-bearing'),speed_kt:num('flight-speed'),climb_ft_min:num('flight-climb')});if(state.aircraft.some(a=>a.aircraft_id===flight.aircraft_id))throw new Error(`Callsign ${flight.aircraft_id} already exists.`);state={version:state.version+1,observed_at:now,aircraft:[...state.aircraft,flight]};selected=flight.aircraft_id;clearPending('Visitor-supplied flight added; the solver now evaluates this world.');setText('builder-feedback',`${flight.aircraft_id} injected. Run traffic or ask the planner to solve.`);void render();}catch(err){setText('builder-feedback',`NOT ADDED: ${err instanceof Error?err.message:String(err)}`);}}
function removeSelected(){running=false;if(state.aircraft.length<=1){setText('builder-feedback','Keep at least one aircraft in the world.');return;}state={version:state.version+1,observed_at:now,aircraft:state.aircraft.filter(a=>a.aircraft_id!==selected)};selected=state.aircraft[0]!.aircraft_id;clearPending('Selected flight removed. Recompute on the remaining live world.');setText('builder-feedback',`${selected} selected; ${state.aircraft.length} aircraft remain.`);void render();}function updatePolicy(){running=false;policy={...policy,min_horizontal_nm:$<HTMLInputElement>('policy-horizontal').valueAsNumber,min_vertical_ft:$<HTMLInputElement>('policy-vertical').valueAsNumber,horizon_min:$<HTMLInputElement>('policy-horizon').valueAsNumber};setText('horizontal-value',`${policy.min_horizontal_nm.toFixed(1)} NM`);setText('vertical-value',`${policy.min_vertical_ft.toLocaleString()} FT`);setText('horizon-value',`${policy.horizon_min.toFixed(1)} MIN`);clearPending('Safety envelope changed. Re-solve the live world.');void render();}
function exportWorld(){const editor=$<HTMLTextAreaElement>('world-json');editor.value=JSON.stringify(state,null,2);setText('world-json-feedback','Live world exported. Edit tracks, then load your changes.');}
function loadWorld(){try{const next=parseWorldState(JSON.parse($<HTMLTextAreaElement>('world-json').value));running=false;state=next;now=next.observed_at;selected=next.aircraft[0]!.aircraft_id;pending=null;approval=null;audit=new AuditLog();pythonAudit='[]';clearPending('Visitor WorldState loaded. The solver runs on this exact input.');setText('world-json-feedback',`Loaded ${state.aircraft.length} aircraft at version ${state.version}.`);void render();}catch(err){setText('world-json-feedback',`NOT LOADED: ${err instanceof Error?err.message:String(err)}`);}}function perturbTrack(){running=false;clearPending('Track changed. The safety policy is being recomputed from the new vector.');state={version:state.version+1,observed_at:now,aircraft:state.aircraft.map(a=>a.aircraft_id===selected?{...a,vx_nm_min:a.vx_nm_min+0.4,vy_nm_min:a.vy_nm_min+0.3}:a)};void render();}
async function runPlanner(){running=false;busy=true;setText('python-status','Loading real TowerOps Python… (first run only)');await render();try{const result=await towerPython({op:'plan',state,now,policy});const plan:Advisory|null=result.advisory;setText('python-status','Live CPython · towerops.py · AdvisoryPlanner');if(!plan){const has=conflictPairs(state,policy).length>0;clearPending(has?'No admissible maneuver in the bounded candidate set. No state changed.':'No projected conflict. No advisory needed.');if(has)gateScreen='fail';}else{pending=plan;approval=null;proposalMessage='The Python planner found a safe candidate. Review the exact world-bound setpoint, then approve and acknowledge it.';gateScreen='done';gateApproval='wait';gateAck='wait';}}catch(err){clearPending('Python unavailable. No substitute planner or state change.');setText('python-status',String(err));}finally{busy=false;await render();}}
function approvePlan(){if(!pending)return;approval={advisory_hash:pending.advisory_hash,decision:'approve',approved_at:now+0.2,approver:'synthetic-controller'};gateApproval='done';gateAck='wait';proposalMessage='Approval is bound to this advisory hash. Readback is still required before simulated actuation.';void render();}

async function acceptReadback(){if(busy||!pending||!approval)return;const a=pending,applyNow=now+0.5,ack:Ack={advisory_hash:a.advisory_hash,status:'accepted',acknowledged_at:now+0.4};try{busy=true;await render();const result=await towerPython({op:'apply',state,advisory:a,approval,ack,now:applyNow,policy,audit_json:pythonAudit});pythonAudit=result.audit_json;audit.events=result.events as AuditEvent[];if(result.error)throw new GateRejected(result.error);if(!result.valid)throw new Error('Python audit chain verification failed');state=result.state;setText('python-status','Live CPython · ControlRoom.apply · audit verified');now=applyNow;pending=null;approval=null;gateScreen='done';gateApproval='done';gateAck='done';const n=conflictPairs(state,policy).length;proposalMessage=n?`Actuation is simulated; ${n} conflict pair(s) remain. Run another bounded pass.`:'Simulated setpoint applied. No projected conflict remains in the policy window.';}catch(err){proposalMessage=`GATE REJECTED: ${err instanceof GateRejected?err.reason:String(err)}. No state transition was applied.`;pending=null;approval=null;gateScreen='fail';gateAck='fail';}finally{busy=false;}await render();}
function resetWorld(){running=false;policy={...DEFAULT_POLICY};$<HTMLInputElement>('policy-horizontal').value='5';$<HTMLInputElement>('policy-vertical').value='1000';$<HTMLInputElement>('policy-horizon').value='5';state=copy(fixture.state);now=fixture.now;selected='TWR419';trafficSeq=0;pending=null;approval=null;audit=new AuditLog();pythonAudit='[]';gateScreen='wait';gateApproval='wait';gateAck='wait';proposalMessage='Reset to the crossing scenario from demo.py. Run the bounded planner to propose a safe vector.';$<HTMLInputElement>('speed-range').value='1';$('toggle-run').textContent='Run traffic';void render();}
function frame(t:number){if(!lastFrame)lastFrame=t;const elapsed=Math.min(0.08,Math.max(0,(t-lastFrame)/1000));lastFrame=t;if(running){const minutes=elapsed*rate;now+=minutes*60;state={version:state.version+1,observed_at:now,aircraft:state.aircraft.map(a=>projected(a,minutes))};drawAirspace($<HTMLCanvasElement>('airspace'),state,selected,policy);setText('sim-clock',`T+${Math.floor(now-fixture.now)} SEC`);if(t%250<20)void render();}requestAnimationFrame(frame);}
$('toggle-run').addEventListener('click',()=>{running=!running;lastFrame=0;$('toggle-run').textContent=running?'Pause traffic':'Run traffic';if(running)announce('Traffic is moving from its displayed velocity vectors.');else announce('Traffic paused.');});
$('reset-world').addEventListener('click',resetWorld);$('add-traffic').addEventListener('click',addTraffic);$('perturb-track').addEventListener('click',perturbTrack);$('run-planner').addEventListener('click',()=>void runPlanner());$('approve').addEventListener('click',approvePlan);$('readback').addEventListener('click',()=>void acceptReadback());
$('add-custom-flight').addEventListener('click',addCustomFlight);$('remove-selected').addEventListener('click',removeSelected);for(const id of ['policy-horizontal','policy-vertical','policy-horizon'])$(id).addEventListener('input',updatePolicy);$('load-world').addEventListener('click',loadWorld);$('export-world').addEventListener('click',exportWorld);$('verify-audit').addEventListener('click',()=>void audit.verify().then(ok=>setText('audit-verdict',ok?`HASH CHAIN VALID - ${audit.events.length} EVENTS`:'HASH CHAIN INVALID')));$('speed-range').addEventListener('input',e=>{rate=Number((e.currentTarget as HTMLInputElement).value);setText('speed-value',`${rate.toFixed(1)}x`);});
function announce(message:string){setText('announcer',message);}
window.addEventListener('resize',()=>void render());void render();requestAnimationFrame(frame);
